app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired



class MessageForm(FlaskForm):
    """
    Form for users to send message
    """
    message = StringField(validators=[DataRequired()])
    submit = SubmitField()

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user',__name__)

from . import views, friends, groups, conversations

app/user/views.py
from flask import abort, render_template, request, url_for, redirect
from flask_login import current_user, login_required

import requests

from . import user
from .forms import MessageForm
from ..models import User, Conversation, Message, GroupConversation, MessageSchema
from .friends import get_all_Friends, get_all_users_not_friends, addFriend
from .conversations import get_all_conversations, get_conversation, get_messages_by_conversation, create_conversation, accept_conversation, delete_conversation, send_message_to_conversation

import json

messages_schema=MessageSchema(many=True)

@user.route('/chat/<int:uid>')
def chat(uid):
    """
    Render the homepage template on the /chat route
    """
    form = MessageForm()
    conversations = get_all_conversations().get_json()

    active_conversation = -1

    if len(conversations) > 0:
        active_conversation = conversations[0]

        return redirect(url_for('user.chat_with', uid=uid, conversation_id=active_conversation['id']))

    else:
        return render_template('user/chat.html', title="Chat", username=User.query.get_or_404(uid).username,
                               conversations=[], messages=[], current_conversation=None,
                               form=form)


@user.route('/chat/<int:uid>/c/<int:conversation_id>', methods=['GET'])
def chat_with(uid, conversation_id):
    form = MessageForm()
    conversations = get_all_conversations().get_json()
    active_conversation = get_conversation(conversation_id).get_json()

    return render_template('user/chat.html', title="Chat",
                           username=User.query.get_or_404(uid).username,
                           conversations=conversations, current_conversation=active_conversation,
                           form=form)

@user.route('/conversations/<int:conversation_id>/messages')
def render_conversation_messages(conversation_id):
    active_conversation = get_conversation(conversation_id).get_json()
    messages = get_messages_by_conversation(
        conversation_id).get_json()

    messages_model = messages_schema.load(messages).data
    return render_template('user/chathistory.html',messages=messages_model,current_conversation=active_conversation)

app/templates/user/chat.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Chat{% endblock %}
{% block body %}

<div class="container-chat">
  <aside class="sidebar">
    <div class="user-section">
      <div class="user-data">
        <div class="user-img"></div>
        <div class="username"> <span>{{ current_user.username }}</span></div>
      </div>
      <ul id="list-tabs" class="nav nav-tabs">
        <li class="nav-item">
          <a id="link-convs" class="nav-link active">Convs</a>
        </li>
        <li class="nav-item">
          <a id="link-friends" class="nav-link">Friends</a>
        </li>
      </ul>
    </div>
    <div id="content-holder" class="content-user">
      <div id="list-convs" class="active-content">
        {% for conv in conversations %}
        <div>
          <div class="user-img"></div>
          <div class="username">
            {% if conv['user1']['id'] == current_user.id %}
            <a href="{{ url_for('user.chat_with',uid=current_user.id, conversation_id=conv['id']) }}">
              {{ conv['user2']['username'] }}</a>
            {% else %}
            <a href="{{ url_for('user.chat_with',uid=current_user.id, conversation_id=conv['id']) }}">
              {{ conv['user1']['username'] }}</a>
            {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
      <div id="list-friends">
        {% for friend in friends%}
        <div>
          <div class="user-img"></div>
          <div class="username">
            {% if friend['user1']['id'] == current_user.id %}
            <span>{{ friend['user2']['username'] }}</span>
            {% else %}
            <span>{{ friend['user1']['username'] }}</span>
            {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </aside>
  <main class="main-chat">
    <div class="chat">
      {% if current_conversation %}
      <ul id="chat-history" class="chat-history">
        
      </ul>
      {% endif %}
    </div>
    <div class="form-chat">
      <form id="form-message" method="POST" action="">
        {{ form.csrf_token }}
        {{ form.message.label }} {{ form.message(size=20) }}
        <input type="submit" value="Submit">
      </form>
    </div>
  </main>
</div>

<script type="text/javascript" charset="utf-8">
  var socket = io.connect('http://' + document.domain + ':' + location.port);
  socket.on('connect', function () {
    socket.emit('connect-client', {
      data: 'User Connected'
    });
    $.ajax({
      url: "{{ url_for('user.render_conversation_messages', conversation_id=current_conversation['id']) }}",
      type: "get",
      success: function (response) {
        $("#chat-history").html(response);
      },
      error: function (xhr) {
        console.log("error");
      }
    });
    var form = $('#form-message').on('submit', function (e) {
      e.preventDefault()
      let user_input = $('#message').val();
      socket.emit('send-message', {
        id_conv: '{{current_conversation["id"]}}',
        id_current_user:'{{current_user.id}}',
        message: user_input
      })
      $('input.message').val('').focus()
    })
  })
  socket.on('refresh-messages', function (data) {
    $.ajax({
      url: "{{ url_for('user.render_conversation_messages', conversation_id=current_conversation['id']) }}",
      type: "get",
      success: function (response) {
        $("#chat-history").html(response);
      },
      error: function (xhr) {
        console.log("error");
      }
    });
  });
</script>
{% endblock %}

app/templates/user/chathistory.html
{% for message in messages%}
{% if message['user_id'] == current_user.id %}
<li class="clearfix">
    <div class="message-data align-right">
        <span class="message-data-time">{{message.time | formatdatetime}}</span> &nbsp; &nbsp;
        <span class="message-data-name">{{current_user.username}}</span> <i class="fa fa-circle me"></i>
    </div>
    <div class="message  my-message  float-right">
        {{message.reply}}
    </div>
</li>
{% else %}
<li>
    <div class="message-data">
        {% if current_conversation['user1']['id'] == current_user.id %}
        <span class="message-data-name"><i class="fa fa-circle online"></i>
            {{current_conversation['user2']['username']}}</span>
        {% else %}
        <span class="message-data-name"><i class="fa fa-circle online"></i>
            {{current_conversation['user1']['username']}}</span>
        {% endif %}
        <span class="message-data-time">{{message.time | formatdatetime}}</span>
    </div>
    <div class="message other-message">
        {{message.reply}}
    </div>
</li>
{% endif %}
{% endfor %}